### 创建新用户
POST http://localhost:3000/new-user
Content-Type: application/json

{
    "nickName":"first-friend",
    "avatar":"https://avataaars.io/?avatarStyle=Circle"
}

### 添加新瞬间
POST http://localhost:3000/new-moment
Content-Type: application/json

{
    "userId":"100000",
    "content":"中文瞬间"
}

### 删除瞬间
POST http://localhost:3000/remove-moment
Content-Type: application/json

{
    "userId":"100000",
    "momentId":"2fdfa4d1-c6e1-4d94-95b2-61d8e3ad3e9c"
}

### 添加新朋友
POST http://localhost:3000/new-friend
Content-Type: application/json

{
    "userId":"100000",
    "friendId":"100001"
}

### 删除朋友
POST http://localhost:3000/remove-friend
Content-Type: application/json

{
    "userId":"100000",
    "friendId":"100001"
}

### 查询近况
POST http://localhost:3000/recent
Content-Type: application/json

{
    "userId":"100000"
}

### 查询朋友
POST http://localhost:3000/friends
Content-Type: application/json

{
    "userId":"100000"
}

### 查询所有瞬间
POST http://localhost:3000/moments
Content-Type: application/json

{
    "userId":"100000"
}