### 创建新用户
POST http://localhost:3000/new-user
Content-Type: application/json

{
    "nickName":"first-friend",
    "avatar":"https://avataaars.io/?avatarStyle=Circle",
    "password":"66666"
}

### 创建 token
POST http://localhost:3000/new-token
Content-Type: application/json

{
    "userId":"100000",
    "password":"666666"
}

### 查询当前用户
POST http://localhost:3000/current-user

### 添加新瞬间
POST http://localhost:3000/new-moment
Content-Type: application/json

{
    "content":"范范大魔王的傲娇日常"
}

### 删除瞬间
POST http://localhost:3000/remove-moment
Content-Type: application/json

{
    "momentId":"2fdfa4d1-c6e1-4d94-95b2-61d8e3ad3e9c"
}

### 添加新朋友
POST http://localhost:3000/new-friend
Content-Type: application/json

{
    "friendUserId":"100001"
}

### 删除朋友
POST http://localhost:3000/remove-friend
Content-Type: application/json

{
    "friendId":"73e756e7-c59d-4e4d-94e9-5206ccf7fb58"
}

### 查询近况
POST http://localhost:3000/recent

### 查询朋友
POST http://localhost:3000/friends

### 查询账号拥有者的所有瞬间
POST http://localhost:3000/owner-moments
Content-Type: application/json

### 查询朋友的所有瞬间
POST http://localhost:3000/friend-moments
Content-Type: application/json

{
    "friendId":"df5e1edc-a412-4c1e-b898-81c5b1a3c1ac"
}